# Generated by Django 6.0.6 on 2026-06-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_order_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='p_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
